name: e_tutor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  equatable: ^2.0.7
  authentication_repository:
    path: packages/authentication_repository
  flutter_bloc: ^8.1.6
  flow_builder: ^0.1.0
  formz: ^0.8.0
  form_inputs:
    path: packages/form_inputs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
