name: profile_repository
description: Dart package which manages profile
publish_to: none

environment:
  sdk: "^3.5.4"

dependencies:
  formz: ^0.8.0
  equatable: ^2.0.7
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.7